//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PizzaAppData.HelperClasses
{
	/// <summary>Field Creation Class for entity OrdersListEntity</summary>
	public partial class OrdersListFields
	{
		/// <summary>Creates a new OrdersListEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrdersListFieldIndex.Id); }}
		/// <summary>Creates a new OrdersListEntity.TotalPrice field instance</summary>
		public static EntityField2 TotalPrice { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrdersListFieldIndex.TotalPrice); }}
	}

	/// <summary>Field Creation Class for entity PizzaSideEntity</summary>
	public partial class PizzaSideFields
	{
		/// <summary>Creates a new PizzaSideEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSideFieldIndex.Id); }}
		/// <summary>Creates a new PizzaSideEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSideFieldIndex.Price); }}
		/// <summary>Creates a new PizzaSideEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSideFieldIndex.Type); }}
	}

	/// <summary>Field Creation Class for entity PizzaSizeEntity</summary>
	public partial class PizzaSizeFields
	{
		/// <summary>Creates a new PizzaSizeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSizeFieldIndex.Id); }}
		/// <summary>Creates a new PizzaSizeEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSizeFieldIndex.Price); }}
		/// <summary>Creates a new PizzaSizeEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSizeFieldIndex.Type); }}
	}

	/// <summary>Field Creation Class for entity PizzasListEntity</summary>
	public partial class PizzasListFields
	{
		/// <summary>Creates a new PizzasListEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.Id); }}
		/// <summary>Creates a new PizzasListEntity.OrderId field instance</summary>
		public static EntityField2 OrderId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.OrderId); }}
		/// <summary>Creates a new PizzasListEntity.PricePerPizza field instance</summary>
		public static EntityField2 PricePerPizza { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.PricePerPizza); }}
		/// <summary>Creates a new PizzasListEntity.Side field instance</summary>
		public static EntityField2 Side { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.Side); }}
		/// <summary>Creates a new PizzasListEntity.Size field instance</summary>
		public static EntityField2 Size { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.Size); }}
		/// <summary>Creates a new PizzasListEntity.Topping field instance</summary>
		public static EntityField2 Topping { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.Topping); }}
	}

	/// <summary>Field Creation Class for entity PizzaToppingEntity</summary>
	public partial class PizzaToppingFields
	{
		/// <summary>Creates a new PizzaToppingEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaToppingFieldIndex.Id); }}
		/// <summary>Creates a new PizzaToppingEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaToppingFieldIndex.Price); }}
		/// <summary>Creates a new PizzaToppingEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaToppingFieldIndex.Type); }}
	}
	

}