//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace OrderView.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'OrdersList'.</summary>
	[Serializable]
	[DataContract]
	public partial class Pizza
	{
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'OrdersList.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the PizzasLists field. </summary>
		[DataMember]
		public List<PizzaTypes.PizzasList> PizzasLists { get; set; }
		/// <summary>Gets or sets the TotalPrice field. Derived from Entity Model Field 'OrdersList.TotalPrice'</summary>
		[DataMember]
		public System.Double TotalPrice { get; set; }
	}

	namespace PizzaTypes
	{
		/// <summary> DTO class which is derived from the entity 'PizzasList (PizzasLists)'.</summary>
		[Serializable]
		[DataContract]
		public partial class PizzasList
		{
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'PizzasList.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the OrderId field. Derived from Entity Model Field 'PizzasList.OrderId (FK)'</summary>
			[DataMember]
			public System.Int32 OrderId { get; set; }
			/// <summary>Gets or sets the PricePerPizza field. Derived from Entity Model Field 'PizzasList.PricePerPizza'</summary>
			[DataMember]
			public System.Double PricePerPizza { get; set; }
			/// <summary>Gets or sets the Side field. Derived from Entity Model Field 'PizzasList.Side'</summary>
			[DataMember]
			public System.String Side { get; set; }
			/// <summary>Gets or sets the Size field. Derived from Entity Model Field 'PizzasList.Size'</summary>
			[DataMember]
			public System.String Size { get; set; }
			/// <summary>Gets or sets the Topping field. Derived from Entity Model Field 'PizzasList.Topping'</summary>
			[DataMember]
			public System.String Topping { get; set; }
		}
	}

}




