//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using PizzaAppData.EntityClasses;
using PizzaAppData.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace PizzaAppData.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the OrdersList entity</summary>
		public EntityQuery<OrdersListEntity> OrdersList { get { return Create<OrdersListEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the PizzaSide entity</summary>
		public EntityQuery<PizzaSideEntity> PizzaSide { get { return Create<PizzaSideEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the PizzaSize entity</summary>
		public EntityQuery<PizzaSizeEntity> PizzaSize { get { return Create<PizzaSizeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the PizzasList entity</summary>
		public EntityQuery<PizzasListEntity> PizzasList { get { return Create<PizzasListEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the PizzaTopping entity</summary>
		public EntityQuery<PizzaToppingEntity> PizzaTopping { get { return Create<PizzaToppingEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}