//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PizzaAppData.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitOrdersListEntityMappings();
			InitPizzaSideEntityMappings();
			InitPizzaSizeEntityMappings();
			InitPizzasListEntityMappings();
			InitPizzaToppingEntityMappings();
		}

		/// <summary>Inits OrdersListEntity's mappings</summary>
		private void InitOrdersListEntityMappings()
		{
			this.AddElementMapping("OrdersListEntity", @"pizza_app", @"public", "orders_list", 2, 0);
			this.AddElementFieldMapping("OrdersListEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.orders_list_id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("OrdersListEntity", "TotalPrice", "total_price", false, "Double", 0, 38, 0, false, "", null, typeof(System.Double), 1);
		}

		/// <summary>Inits PizzaSideEntity's mappings</summary>
		private void InitPizzaSideEntityMappings()
		{
			this.AddElementMapping("PizzaSideEntity", @"pizza_app", @"public", "pizza_sides", 3, 0);
			this.AddElementFieldMapping("PizzaSideEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.pizza_sides_id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("PizzaSideEntity", "Price", "price", false, "Double", 0, 38, 0, false, "", null, typeof(System.Double), 1);
			this.AddElementFieldMapping("PizzaSideEntity", "Type", "type", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits PizzaSizeEntity's mappings</summary>
		private void InitPizzaSizeEntityMappings()
		{
			this.AddElementMapping("PizzaSizeEntity", @"pizza_app", @"public", "pizza_sizes", 3, 0);
			this.AddElementFieldMapping("PizzaSizeEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.pizza_sizes_id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("PizzaSizeEntity", "Price", "price", false, "Double", 0, 38, 0, false, "", null, typeof(System.Double), 1);
			this.AddElementFieldMapping("PizzaSizeEntity", "Type", "type", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits PizzasListEntity's mappings</summary>
		private void InitPizzasListEntityMappings()
		{
			this.AddElementMapping("PizzasListEntity", @"pizza_app", @"public", "pizzas_list", 6, 0);
			this.AddElementFieldMapping("PizzasListEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.pizzas_list_id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("PizzasListEntity", "OrderId", "order_id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("PizzasListEntity", "PricePerPizza", "price_per_pizza", false, "Double", 0, 38, 0, false, "", null, typeof(System.Double), 2);
			this.AddElementFieldMapping("PizzasListEntity", "Side", "side", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("PizzasListEntity", "Size", "size", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("PizzasListEntity", "Topping", "topping", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 5);
		}

		/// <summary>Inits PizzaToppingEntity's mappings</summary>
		private void InitPizzaToppingEntityMappings()
		{
			this.AddElementMapping("PizzaToppingEntity", @"pizza_app", @"public", "pizza_toppings", 3, 0);
			this.AddElementFieldMapping("PizzaToppingEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.pizza_toppings_id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("PizzaToppingEntity", "Price", "price", false, "Double", 0, 38, 0, false, "", null, typeof(System.Double), 1);
			this.AddElementFieldMapping("PizzaToppingEntity", "Type", "type", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
		}

	}
}
